// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package notify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeysGeneratedRequest struct {
	KeysGenerated        int32    `protobuf:"varint,1,opt,name=keys_generated,json=keysGenerated,proto3" json:"keys_generated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysGeneratedRequest) Reset()         { *m = KeysGeneratedRequest{} }
func (m *KeysGeneratedRequest) String() string { return proto.CompactTextString(m) }
func (*KeysGeneratedRequest) ProtoMessage()    {}
func (*KeysGeneratedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{0}
}

func (m *KeysGeneratedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysGeneratedRequest.Unmarshal(m, b)
}
func (m *KeysGeneratedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysGeneratedRequest.Marshal(b, m, deterministic)
}
func (m *KeysGeneratedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysGeneratedRequest.Merge(m, src)
}
func (m *KeysGeneratedRequest) XXX_Size() int {
	return xxx_messageInfo_KeysGeneratedRequest.Size(m)
}
func (m *KeysGeneratedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysGeneratedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeysGeneratedRequest proto.InternalMessageInfo

func (m *KeysGeneratedRequest) GetKeysGenerated() int32 {
	if m != nil {
		return m.KeysGenerated
	}
	return 0
}

type KeysGeneratedResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysGeneratedResponse) Reset()         { *m = KeysGeneratedResponse{} }
func (m *KeysGeneratedResponse) String() string { return proto.CompactTextString(m) }
func (*KeysGeneratedResponse) ProtoMessage()    {}
func (*KeysGeneratedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba76cc4ebe272d4, []int{1}
}

func (m *KeysGeneratedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysGeneratedResponse.Unmarshal(m, b)
}
func (m *KeysGeneratedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysGeneratedResponse.Marshal(b, m, deterministic)
}
func (m *KeysGeneratedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysGeneratedResponse.Merge(m, src)
}
func (m *KeysGeneratedResponse) XXX_Size() int {
	return xxx_messageInfo_KeysGeneratedResponse.Size(m)
}
func (m *KeysGeneratedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysGeneratedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeysGeneratedResponse proto.InternalMessageInfo

func (m *KeysGeneratedResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*KeysGeneratedRequest)(nil), "KeysGeneratedRequest")
	proto.RegisterType((*KeysGeneratedResponse)(nil), "KeysGeneratedResponse")
}

func init() {
	proto.RegisterFile("notify.proto", fileDescriptor_aba76cc4ebe272d4)
}

var fileDescriptor_aba76cc4ebe272d4 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcb, 0x2f, 0xc9,
	0x4c, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe5, 0x12, 0xf1, 0x4e, 0xad, 0x2c,
	0x76, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c, 0x49, 0x4d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0x11, 0x52, 0xe5, 0xe2, 0xcb, 0x4e, 0xad, 0x2c, 0x8e, 0x4f, 0x87, 0x49, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x06, 0xf1, 0x66, 0x23, 0xab, 0x56, 0x32, 0xe4, 0x12, 0x45, 0xd3, 0x5e, 0x5c, 0x90,
	0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x0a, 0xd6,
	0xc8, 0x19, 0x04, 0xe3, 0x1a, 0x85, 0x71, 0xf1, 0x05, 0xa5, 0xa6, 0x67, 0xe6, 0xe7, 0x25, 0xe6,
	0x04, 0xa7, 0x16, 0x95, 0xa5, 0x16, 0x09, 0xb9, 0x70, 0x09, 0xfb, 0x81, 0xdd, 0x84, 0x62, 0x94,
	0x90, 0xa8, 0x1e, 0x36, 0x97, 0x49, 0x89, 0xe9, 0x61, 0xb5, 0xd1, 0x49, 0x39, 0x4a, 0x31, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0x3d, 0x31, 0x29, 0xdf, 0xd8, 0xd0,
	0xc0, 0x58, 0x1f, 0xec, 0xcd, 0x62, 0x7d, 0x88, 0xa7, 0x93, 0xd8, 0xc0, 0x5c, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x03, 0x76, 0x6c, 0xe6, 0x05, 0x01, 0x00, 0x00,
}
